version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    container_name: mysql
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DATABASE: QuangCaoDieuHoa
    privileged: false
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql:rw
    networks:
      - app-network

  backend:
    container_name: backend
    image: ndvinhcn/web-dieu-hoa:quangcaodieuhoademo
    restart: always
    depends_on:
      - db
    ports:
      - "51926:51926"  
    networks:
      - app-network

  frontend:
    container_name: frontend
    image:  ndvinhcn/web-dieu-hoa:frontend  # Thay đổi tên và tag tương ứng
    ports:
      - "3000:3000"
    networks:
      - app-network

  webuser:
    container_name: webuser
    image: vanhng/webdieuhoa:web-user
    ports:
      - "3001:3001"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - webuser
    networks:
      - app-network