version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  nginxproxymanager-data:
  nginxproxymanager-ssl:

services: 
  db:
    container_name: mysql
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DATABASE: QuangCaoDieuHoa
    privileged: false
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql:rw
    networks:
      - app-network

  backend:
    container_name: backend
    image: backend-ssl
    build:
      context: ./backend/QuangCaoDieuHoaAPI
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "51926:51926"  
      - "51927:51927"  
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-ssl  # Thay đổi tên và tag tương ứng
    ports:
      - "3000:3000"
    networks:
      - app-network

  # webuser:
  #   container_name: webuser
  #   image: vanhng/webdieuhoa:web-user
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - app-network

  # nginx:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   ports:
  #     - "80:80"
  #     - "81:81"
  #     - "443:443"
  #   depends_on:
  #     - backend
  #     - frontend
  #     - webuser
  #   volumes:
  #     - nginxproxymanager-data:/data
  #     - nginxproxymanager-ssl:/etc/letsencrypt
  #   networks:
  #     - app-network

